version: "3.7"

networks:
  mole: {}

services:

  oathkeeper:
    image: oryd/oathkeeper:v0.40.0
    depends_on:
      - kratos
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: on-failure
    volumes:
      - ./infrastructure/oathkeeper:/etc/config/oathkeeper
    labels:
      - traefik.enable=true
      - traefik.http.routers.oathkeeper.rule=Host(`oathkeeper`)
      - traefik.http.routers.oathkeeper.entrypoints=web
      - traefik.http.routers.oathkeeper.service=oathkeeper
      - traefik.http.services.oathkeeper.loadbalancer.server.port=4456
      - traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions
      - traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-Id-Token,Authorization
    networks:
      - mole

  postgres-kratos:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    ports:
      - "5432:5432"
    volumes:
      - "./infrastructure/postgres-kratos:/var/lib/postgresql/data"
    networks:
      - mole

  kratos-migrate:
    image: oryd/kratos:v0.11.0
    depends_on:
      - postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./infrastructure/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - mole

  kratos:
    image: oryd/kratos:v0.11.0
    depends_on:
      - kratos-migrate
      - postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEAK_SENSITIVE_VALUES=true
    ports:
      - '4433:4433'
      - '4434:4434'
    volumes:
      - type: bind
        source: ./infrastructure/kratos/email-password
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - mole

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.11.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    ports:
      - "4455:3000"
    networks:
      - mole