version: '3'

networks:
  mole: {}

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=mole
      - POSTGRES_PASSWORD=mole
      - POSTGRES_DB=post-service
    ports:
      - "5433:5432"
    volumes:
      - "./infrastructure/postgres-post-service:/var/lib/postgresql/data"
    networks:
      - mole
  
  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_USERNAME=mole
      - RABBITMQ_PASSWORD=mole
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./infrastructure/rabbitmq-post-service:/bitnami"
    networks:
      - mole
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mole
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 8085:8085
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mole
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - "kafka"
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - mole