version: '3'

networks:
  mole: {}

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=mole
      - POSTGRES_PASSWORD=mole
      - POSTGRES_DB=post-service
    ports:
      - "5433:5432"
    volumes:
      - "./infrastructure/postgres-post-service:/var/lib/postgresql/data"
    networks:
      - mole
  
  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_USERNAME=mole
      - RABBITMQ_PASSWORD=mole
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./infrastructure/rabbitmq-post-service:/bitnami"
    networks:
      - mole
  
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 22181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mole
  
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092, EXTERNAL://:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - mole
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - "kafka"
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - mole