server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mole-auth?createDatabaseIfNotExist=true
    username: mole
    password: mole
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
keycloak:
  realm: mole
  auth-server-url: http://localhost:8080
  ssl-required: none
  resource: mole
  credentials:
    secret: wRlc9SedbKfDr9xwWqnbzVOLJI7STYl1
  use-resource-role-mappings: true
  bearer-only: true